[project]
name = "organizador-de-facturas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mepystho066", email = "mepystho06@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
organizador-de-facturas = "organizador_de_facturas:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
